package nomes;

public enum NomeLiga {
	//norte
	INGLATERRA, ITALIA, ALEMANHA_HOLANDA, ESPANHA_FRANCA_PORTUGUAL, 
	//oeste
	BRASIL, ARGENTINA, URUGUAI_COLOMBIA, CHILE_EQUADOR_PARAGUAI,	
	//leste
	CHINA_ISRAEL_CATAR, JAPAO_COREIASUL, MEXICO_EUA_COSTARICA_CANADA, EMIRADOSAU_ASAUDITA_IRA,
	//sul
	AUSTRALIA_NOVAZELANDIA, EGITO_NIGERIA_COSTAMARFIM, MARROCOS_AFRICASUL_TUNISIA, RDCONGO_CAMAROES,
}
