package nomes;

public enum NomeLiga {
	//norte
	INGLES, ITALIANO, ALEMAO_HOLANDES, ESPANHOL_FRANCES_PORTUGUES, 
	//oeste
	BRASILEIRO, ARGENTINO, URUGUAIO_COLOMBIANO, CHILENO_EQUATORIANO_PARAGUAI,	
	//leste
	CHINES_ISRAEL_CATAR, JAPONES_COREIASUL, MEXICANO_EUA_COSTARICA_CANADA, EMIRADOSAU_ASAUDITA_IRA,
	//sul
	AUSTRALIA_NOVAZELANDIA, EGITO_NIGERIA_COSTAMARFIM, MARROCOS_AFRICASUL_TUNISIA, RDCONGO_CAMAROES,
}
