package nomes;

public enum Paises {
	//NORTE
	INGLATERRA, ITALIA, ALEMANHA, ESPANHA, FRANCA, PORTUGAL, HOLANDA,
	//OESTE
	BRASIL, ARGENTINA, URUGUAI, CHILE, COLOMBIA, EQUADOR, PARAGUAI,
	//LESTE
	EMIRADOS_ARABES_UNIDOS, ARABIA_SAUDITA, IRA, CHINA, JAPAO, COREIA_SUL, CATAR, ISRAEL,
	EUA, CANADA, MEXICO, COSTA_RICA,
	//SUL
	AUSTRALIA, NOVA_ZELANDIA,
	EGITO, RD_CONGO, MARROCOS, CAMAROES, TUNISIA, NIGERIA, COSTA_MARFIM, AFRICA_SUL,
	
}
